# -*- coding: utf-8 -*-
"""operations.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cc_YHHyyga5sNEIIW4k9vMUWhCiwTtEk
"""

# model_operations.py
def save_model(model, path):
    model.save(path)

def load_model(path):
    return load_model(path)
def lrgb(img):
    nimg = np.zeros((img.shape[0], img.shape[1], 3))
    for i in range(img.shape[2]):
        c = img[:, :, i]
        col = colors[i]

        for j in range(3):
            nimg[:, :, j] += col[j] * c
    nimg = nimg / 255.0
    return nimg

def save_masks(test_ds):
    k = 0
    paths = get_image_paths("path to save predicted masks")
    for imgs in test_ds:
        p = model.predict(imgs)
        for i in range(p.shape[0]):
            arg = np.argmax(p[i], axis=-1)
            _s = pre_process(arg)
            _p = lrgb(_s)
            filename = paths[k].split("/")[-1]
            k += 1
            plt.imsave(filename, _p)