# -*- coding: utf-8 -*-
"""ssl.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OpHT1e3dmeZGQyZLv9Hl6p_bC3fQDRts
"""

import torch
import torch.nn as nn
from torchvision import models

class SwAVModel(nn.Module):
    def __init__(self, base_encoder, projection_dim=256):
        super(SwAVModel, self).__init__()
        self.encoder = nn.Sequential(
            *list(base_encoder.children())[:-1]
        )


        in_features = base_encoder.fc.in_features
        self.projection_head = nn.Linear(in_features, projection_dim)

    def forward(self, x):
        features = self.encoder(x)
        features = features.view(features.size(0), -1)
        projections = self.projection_head(features)
        return features, projections