# -*- coding: utf-8 -*-
"""visualization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vsIA9gRbfMa57lV_kxtxnoE0rhzEzTnm
"""

# visualization.py
def visualize_predictions(model, test_ds, max_show=10):
    for imgs, segs in test_ds:
        p = model.predict(imgs)
        for i in range(p.shape[0]):
            if i > max_show:
                break

            plt.figure(figsize=(15, 5))
            plt.subplot(131)
            plt.title("Actual Image")
            plt.imshow(imgs[i])

            plt.subplot(132)
            plt.title("Masked Image")
            plt.imshow(np.argmax(segs[i], axis=-1), cmap='viridis')

            plt.subplot(133)
            plt.title("Predicted Image")
            plt.imshow(np.argmax(p[i], axis=-1), cmap='viridis')

            plt.show()
        break